<?php

namespace Database\Seeders;

use App\Models\Employer\Employer;
use App\Models\Industry;
use App\Models\Vacancies\Vacancy;
use Illuminate\Database\Seeder;

class VacancySeeder extends Seeder
{
    public function run(): void
    {
        // Ensure industries exist
        $industries = [
            ['name' => 'Информационные технологии (IT)', 'slug' => 'it'],
            ['name' => 'Образование', 'slug' => 'education'],
            ['name' => 'Здравоохранение', 'slug' => 'healthcare'],
            ['name' => 'Строительство', 'slug' => 'construction'],
            ['name' => 'Финансы и бухгалтерия', 'slug' => 'finance&accounting'],
            ['name' => 'Производство', 'slug' => 'production'],
            ['name' => 'Логистика и транспорт', 'slug' => 'logistics&transport'],
            ['name' => 'Маркетинг и реклама', 'slug' => 'marketing&ads'],
            ['name' => 'Сельское хозяйство', 'slug' => 'agricultural'],
            ['name' => 'Туризм и гостиницы', 'slug' => 'tourism&hotels'],
            ['name' => 'Государственная служба', 'slug' => 'public_service'],
            ['name' => 'Другое', 'slug' => 'other'],
        ];

        foreach ($industries as $industry) {
            Industry::firstOrCreate(['slug' => $industry['slug']], ['name' => $industry['name']]);
        }

        // Create 7 employers
        $employers = [
            [
                'user_id' => 1,
                'type' => 'company',
                'company_name' => 'Tajik IT Solutions',
                'company_address' => 'г. Душанбе, ул. Рудаки 45',
                'company_website' => 'https://tajikitsolutions.tj',
                'description' => 'IT-компания, специализирующаяся на разработке программного обеспечения.',
                'contact_email' => 'info@tajikitsolutions.tj',
                'contact_phone' => '+992123456789',
            ],
            [
                'user_id' => 2,
                'type' => 'company',
                'company_name' => 'Pamir Education Center',
                'company_address' => 'г. Худжанд, ул. Ленина 12',
                'company_website' => 'https://pamireducation.tj',
                'description' => 'Образовательный центр для школьников и взрослых.',
                'contact_email' => 'contact@pamireducation.tj',
                'contact_phone' => '+992987654321',
            ],
            [
                'user_id' => 3,
                'type' => 'company',
                'company_name' => 'Sihat Medical Clinic',
                'company_address' => 'г. Куляб, ул. Сомони 23',
                'company_website' => 'https://sihatclinic.tj',
                'description' => 'Медицинская клиника, предоставляющая услуги в сельской местности.',
                'contact_email' => 'info@sihatclinic.tj',
                'contact_phone' => '+992112233445',
            ],
            [
                'user_id' => 4,
                'type' => 'company',
                'company_name' => 'Bunyod Construction',
                'company_address' => 'г. Бохтар, ул. Айни 10',
                'company_website' => 'https://bunyodconstruction.tj',
                'description' => 'Строительная компания, специализирующаяся на жилых объектах.',
                'contact_email' => 'bunyod@bunyod.tj',
                'contact_phone' => '+992223344556',
            ],
            [
                'user_id' => 5,
                'type' => 'company',
                'company_name' => 'Somoni Finance',
                'company_address' => 'г. Душанбе, ул. Нисор 15',
                'company_website' => 'https://somonifinance.tj',
                'description' => 'Финансовая компания, предоставляющая услуги учета и консалтинга.',
                'contact_email' => 'info@somonifinance.tj',
                'contact_phone' => '+992334455667',
            ],
            [
                'user_id' => 6,
                'type' => 'company',
                'company_name' => 'Tajik Agro Co',
                'company_address' => 'г. Гиссар, ул. Фирдавси 8',
                'company_website' => 'https://tajikagro.tj',
                'description' => 'Сельскохозяйственная компания, занимающаяся выращиванием культур.',
                'contact_email' => 'agro@tajikagro.tj',
                'contact_phone' => '+992445566778',
            ],
            [
                'user_id' => 7,
                'type' => 'company',
                'company_name' => 'Pamir Travel',
                'company_address' => 'г. Хорог, ул. Памир 5',
                'company_website' => 'https://pamirtravel.tj',
                'description' => 'Туристическая компания, организующая туры по Памиру.',
                'contact_email' => 'travel@pamirtravel.tj',
                'contact_phone' => '+992556677889',
            ],
        ];

        $employerIds = [];
        foreach ($employers as $employerData) {
            $employer = Employer::firstOrCreate(
                ['user_id' => $employerData['user_id']],
                $employerData
            );
            $employerIds[] = $employer->id;
        }

        // Create 20 vacancies distributed across 7 employers
        $vacancies = [
            // Employer 1: Tajik IT Solutions (3 vacancies)
            [
                'employer_id' => $employerIds[0],
                'title' => 'Программист 1С',
                'salary_type' => 'money',
                'salary_start' => 3000,
                'salary_end' => 5000,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'it')->first()->id,
                'description' => 'Настройка и поддержка программ 1С для местных компаний.',
                'benefits' => 'Обучение, стабильная зарплата, работа в офисе.',
                'responsibility' => 'Настройка 1С, обучение пользователей, техническая поддержка.',
                'qualifications' => 'Знание 1С, базовые навыки программирования, знание таджикского и русского языков.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => (['1С', 'Программирование', 'Техподдержка']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[0],
                'title' => 'Технический специалист по IT',
                'salary_type' => 'money',
                'salary_start' => 2500,
                'salary_end' => 4000,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'it')->first()->id,
                'description' => 'Обслуживание компьютерной техники и сетей в офисе.',
                'benefits' => 'Обучение, стабильная зарплата.',
                'responsibility' => 'Настройка оборудования, устранение неполадок.',
                'qualifications' => 'Знание сетей, базовые навыки администрирования.',
                'experience' => '2 года',
                'education' => 'Среднее специальное',
                'skills' => (['Сетевое администрирование', 'Техподдержка']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[0],
                'title' => 'Веб-разработчик',
                'salary_type' => 'money',
                'salary_start' => 3500,
                'salary_end' => 5500,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'it')->first()->id,
                'description' => 'Разработка веб-сайтов для местных компаний.',
                'benefits' => 'Гибкий график, бонусы за проекты.',
                'responsibility' => 'Создание и поддержка веб-сайтов, работа с клиентами.',
                'qualifications' => 'Знание HTML, CSS, JavaScript, знание таджикского языка.',
                'experience' => '2 года',
                'education' => 'Высшее техническое',
                'skills' => (['HTML', 'CSS', 'JavaScript']),
                'type' => 'remote',
                'status' => 'active',
            ],
            // Employer 2: Pamir Education Center (3 vacancies)
            [
                'employer_id' => $employerIds[1],
                'title' => 'Учитель таджикского языка',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'location' => 'Худжанд',
                'industry_id' => Industry::where('slug', 'education')->first()->id,
                'description' => 'Преподавание таджикского языка и литературы в образовательном центре.',
                'benefits' => 'Длинный отпуск, социальный пакет.',
                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
                'qualifications' => 'Знание таджикского языка, педагогическое образование.',
                'experience' => 'Без опыта',
                'education' => 'Высшее педагогическое',
                'skills' => (['Таджикский язык', 'Преподавание']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[1],
                'title' => 'Учитель математики',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'location' => 'Худжанд',
                'industry_id' => Industry::where('slug', 'education')->first()->id,
                'description' => 'Преподавание математики для школьников.',
                'benefits' => 'Длинный отпуск, стабильный график.',
                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
                'qualifications' => 'Педагогическое образование, знание математики.',
                'experience' => 'Без опыта',
                'education' => 'Высшее педагогическое',
                'skills' => (['Математика', 'Преподавание']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[1],
                'title' => 'Преподаватель английского языка',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Худжанд',
                'industry_id' => Industry::where('slug', 'education')->first()->id,
                'description' => 'Преподавание английского языка для взрослых и детей.',
                'benefits' => 'Гибкий график, учебные материалы.',
                'responsibility' => 'Проведение занятий, подготовка материалов.',
                'qualifications' => 'Знание английского языка (B2+), педагогические навыки.',
                'experience' => '1 год',
                'education' => 'Высшее',
                'skills' => (['Английский язык', 'Преподавание']),
                'type' => 'part',
                'status' => 'active',
            ],
            // Employer 3: Sihat Medical Clinic (3 vacancies)
            [
                'employer_id' => $employerIds[2],
                'title' => 'Фельдшер',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Куляб',
                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
                'description' => 'Оказание первой медицинской помощи в сельской клинике.',
                'benefits' => 'Жилье, транспорт до работы.',
                'responsibility' => 'Проведение осмотров, оказание первой помощи.',
                'qualifications' => 'Медицинское образование, сертификат фельдшера.',
                'experience' => '1 год',
                'education' => 'Среднее медицинское',
                'skills' => (['Первая помощь', 'Медицинский уход']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[2],
                'title' => 'Медсестра/Медбрат',
                'salary_type' => 'money',
                'salary_start' => 1800,
                'salary_end' => 2500,
                'location' => 'Куляб',
                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
                'description' => 'Уход за пациентами в больнице.',
                'benefits' => 'Сменный график, соцпакет.',
                'responsibility' => 'Проведение процедур, помощь врачам.',
                'qualifications' => 'Медицинское образование, сертификат.',
                'experience' => '1 год',
                'education' => 'Среднее медицинское',
                'skills' => (['Медицинские процедуры', 'Уход за пациентами']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[2],
                'title' => 'Администратор клиники',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Куляб',
                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
                'description' => 'Организация работы медицинской клиники.',
                'benefits' => 'Стабильная зарплата, соцпакет.',
                'responsibility' => 'Прием пациентов, ведение документации.',
                'qualifications' => 'Навыки общения, знание таджикского и русского языков.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => (['Администрирование', 'Обслуживание клиентов']),
                'type' => 'full',
                'status' => 'active',
            ],
            // Employer 4: Bunyod Construction (3 vacancies)
            [
                'employer_id' => $employerIds[3],
                'title' => 'Бригадир строительной бригады',
                'salary_type' => 'money',
                'salary_start' => 3500,
                'salary_end' => 5000,
                'location' => 'Бохтар',
                'industry_id' => Industry::where('slug', 'construction')->first()->id,
                'description' => 'Руководство строительной бригадой на объектах.',
                'benefits' => 'Жилье на объекте, питание.',
                'responsibility' => 'Координация рабочих, контроль качества строительства.',
                'qualifications' => 'Опыт в строительстве, организаторские навыки.',
                'experience' => '3 года',
                'education' => 'Среднее',
                'skills' => (['Строительство', 'Управление бригадой']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[3],
                'title' => 'Каменщик',
                'salary_type' => 'money',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'location' => 'Бохтар',
                'industry_id' => Industry::where('slug', 'construction')->first()->id,
                'description' => 'Кладка кирпича и блоков на стройке.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Выполнение кладочных работ, соблюдение сроков.',
                'qualifications' => 'Опыт в кладке, физическая выносливость.',
                'experience' => '2 года',
                'education' => 'Среднее',
                'skills' => (['Кладка', 'Строительство']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[3],
                'title' => 'Разнорабочий на стройке',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'location' => 'Бохтар',
                'industry_id' => Industry::where('slug', 'construction')->first()->id,
                'description' => 'Выполнение подсобных работ на строительной площадке.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Помощь в строительных работах, уборка территории.',
                'qualifications' => 'Физическая выносливость.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => (['Физическая работа', 'Строительство']),
                'type' => 'full',
                'status' => 'active',
            ],
            // Employer 5: Somoni Finance (3 vacancies)
            [
                'employer_id' => $employerIds[4],
                'title' => 'Бухгалтер на первичную документацию',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
                'description' => 'Ведение первичной бухгалтерской документации.',
                'benefits' => 'Стабильная зарплата, обучение.',
                'responsibility' => 'Обработка счетов, работа в 1С.',
                'qualifications' => 'Базовое знание бухгалтерии, владение 1С.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => (['1С', 'Бухучет']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[4],
                'title' => 'Финансовый консультант',
                'salary_type' => 'money',
                'salary_start' => 2500,
                'salary_end' => 4000,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
                'description' => 'Консультации по финансовому планированию для местных клиентов.',
                'benefits' => 'Бонусы за результаты, обучение.',
                'responsibility' => 'Работа с клиентами, анализ финансов.',
                'qualifications' => 'Знание финансов, навыки общения, знание таджикского языка.',
                'experience' => '2 года',
                'education' => 'Высшее экономическое',
                'skills' => (['Финансовое планирование', 'Консультации']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[4],
                'title' => 'Кассир',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
                'description' => 'Работа с наличными и безналичными платежами.',
                'benefits' => 'Стабильная зарплата, сменный график.',
                'responsibility' => 'Прием и выдача денег, ведение кассовой документации.',
                'qualifications' => 'Навыки работы с кассой, знание таджикского языка.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => (['Кассовая дисциплина', 'Работа с клиентами']),
                'type' => 'full',
                'status' => 'active',
            ],
            // Employer 6: Tajik Agro Co (3 vacancies)
            [
                'employer_id' => $employerIds[5],
                'title' => 'Фермер-агроном',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Гиссар',
                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
                'description' => 'Выращивание сельскохозяйственных культур.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Уход за посевами, сбор урожая.',
                'qualifications' => 'Опыт в сельском хозяйстве, знание таджикского языка.',
                'experience' => '2 года',
                'education' => 'Среднее',
                'skills' => (['Сельское хозяйство', 'Агрономия']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[5],
                'title' => 'Работник фермы',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'location' => 'Гиссар',
                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
                'description' => 'Работа на ферме по уходу за растениями и животными.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Полив, уход за животными, уборка.',
                'qualifications' => 'Физическая выносливость.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Сельское хозяйство', 'Физическая работа'],
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[5],
                'title' => 'Тракторист',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'location' => 'Гиссар',
                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
                'description' => 'Работа на тракторе для обработки полей.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Обработка полей, обслуживание техники.',
                'qualifications' => 'Удостоверение тракториста, опыт работы.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => (['Трактор', 'Сельское хозяйство']),
                'type' => 'full',
                'status' => 'active',
            ],
            // Employer 7: Pamir Travel (2 vacancies)
            [
                'employer_id' => $employerIds[6],
                'title' => 'Администратор гостевого дома',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'location' => 'Хорог',
                'industry_id' => Industry::where('slug', 'tourism&hotels')->first()->id,
                'description' => 'Обслуживание гостей в гостевом доме на Памире.',
                'benefits' => 'Проживание, питание.',
                'responsibility' => 'Прием гостей, организация их пребывания.',
                'qualifications' => 'Знание таджикского и русского языков, гостеприимство.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => (['Гостеприимство', 'Обслуживание клиентов']),
                'type' => 'full',
                'status' => 'active',
            ],
            [
                'employer_id' => $employerIds[6],
                'title' => 'Гид по Памиру',
                'salary_type' => 'money',
                'salary_start' => 2000,
                'salary_end' => 3500,
                'location' => 'Хорог',
                'industry_id' => Industry::where('slug', 'tourism&hotels')->first()->id,
                'description' => 'Проведение экскурсий по Памирским горам.',
                'benefits' => 'Проживание, питание, бонусы за туры.',
                'responsibility' => 'Проведение экскурсий, обеспечение безопасности туристов.',
                'qualifications' => 'Знание английского или русского, навыки общения.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => (['Экскурсии', 'Коммуникация']),
                'type' => 'part',
                'status' => 'active',
            ],
            // Additional vacancy for 'public_service' industry
            [
                'employer_id' => $employerIds[4],
                'title' => 'Специалист по госзакупкам',
                'salary_type' => 'money',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'location' => 'Душанбе',
                'industry_id' => Industry::where('slug', 'public_service')->first()->id,
                'description' => 'Организация закупок для государственных учреждений.',
                'benefits' => 'Стабильная зарплата, соцпакет.',
                'responsibility' => 'Подготовка документации, участие в тендерах.',
                'qualifications' => 'Знание законодательства о закупках, знание таджикского языка.',
                'experience' => '2 года',
                'education' => 'Высшее',
                'skills' => (['Госзакупки', 'Документооборот']),
                'type' => 'full',
                'status' => 'active',
            ],
            // Additional vacancy for 'other' industry
            [
                'employer_id' => $employerIds[6],
                'title' => 'Портной',
                'salary_type' => 'money',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'location' => 'Хорог',
                'industry_id' => Industry::where('slug', 'other')->first()->id,
                'description' => 'Пошив национальной одежды и ремонт одежды.',
                'benefits' => 'Гибкий график, материалы предоставляются.',
                'responsibility' => 'Пошив, ремонт одежды, работа с клиентами.',
                'qualifications' => 'Навыки шитья, аккуратность.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => (['Шитье', 'Работа с клиентами']),
                'type' => 'full',
                'status' => 'active',
            ],
        ];

        foreach ($vacancies as $vacancy) {
            Vacancy::create($vacancy);
        }
    }
}
